/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.common.workstation.validation;

import org.eclipse.emf.common.util.EList;
import org.limepepper.chefclipse.common.cookbook.CookbookVersion;
import org.limepepper.chefclipse.common.knife.KnifeConfig;
import org.limepepper.chefclipse.common.workstation.CookbooksFolder;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.common.workstation.Repository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RepositoryValidator {
	boolean validate();

	boolean validateOS(String value);
	boolean validateBasepath(String value);
	boolean validateCookbooks(EList<CookbookVersion> value);
	boolean validateKnives(EList<KnifeConfig> value);

	boolean validateKnife(EList<KnifeConfig> value);
	boolean validateCookbookFolders(EList<CookbooksFolder> value);
}
