/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.utility.validation;

import java.io.File;
import java.net.URL;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.utility.Config}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigValidator {
	boolean validate();

	boolean validateChef_server_url(URL value);
	boolean validateClient_key(File value);
	boolean validateNode_name(String value);
	boolean validateLog_level(String value);
	boolean validateValidation_key(File value);
	boolean validateVersion(String value);
	boolean validateValidation_client_name(String value);
}
