/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.common.chefserver.validation;

import org.eclipse.core.resources.IResource;
import org.limepepper.chefclipse.common.chefserver.DataBag;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.common.chefserver.DataBagItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataBagItemValidator {
	boolean validate();

	boolean validateDataBag(DataBag value);

	boolean validateJsonResource(IResource value);
}
