/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.common.chefserver.validation;

import org.limepepper.chefclipse.common.chefserver.Environment;
import org.limepepper.chefclipse.common.chefserver.RunList;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.common.chefserver.Role}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoleValidator {
	boolean validate();

	boolean validateRun_list(RunList value);
	boolean validateEnvironment(Environment value);
}
