/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.common.chefserver.validation;

import org.eclipse.emf.common.util.EList;
import org.limepepper.chefclipse.common.chefserver.Environment;
import org.limepepper.chefclipse.common.chefserver.Node;
import org.limepepper.chefclipse.common.chefserver.Role;
import org.limepepper.chefclipse.common.chefserver.RunList;
import org.limepepper.chefclipse.common.chefserver.RunListItem;
import org.limepepper.chefclipse.common.chefserver.Server;
import org.limepepper.chefclipse.common.cookbook.Recipe;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.common.chefserver.RunList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RunListValidator {
	boolean validate();

	boolean validateNode(Node value);
	boolean validateEnvironment(Environment value);
	boolean validateRole(Role value);
	boolean validateRecipes(EList<Recipe> value);
	boolean validateRun_list_items(EList<RunListItem> value);

	boolean validateRun_list(EList<RunList> value);

	boolean validateServer(Server value);

	boolean validateRun_list(RunList value);
}
