/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.common.chefserver.validation;

import org.limepepper.chefclipse.common.knife.KnifeConfig;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.common.chefserver.ServerCookbookVersion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServerCookbookVersionValidator {
	boolean validate();

	boolean validateVersion(String value);

	boolean validateCookbook_name(String value);

	boolean validateKnifeConfig(KnifeConfig value);
}
