<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="chefserver"
    nsURI="http://limepepper.org/chefclipse/0.0.1/chefserver"
    nsPrefix="chefserver">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Environment"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DataBag"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Role"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Node">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="run_list"
        upperBound="-1"
        eType="#//RunList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Server">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="cookbooks"
        upperBound="-1"
        eType="ecore:EClass cookbook.ecore#//Cookbook"
        unsettable="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="roles"
        eType="#//Role"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Ohai"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Platform"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RunList"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ChefConfig"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Search"/>
</ecore:EPackage>
