<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="knife" nsURI="http://limepepper.org/chefclipse/knife" nsPrefix="org.limepepper.chefclipse">
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plugins" upperBound="-1"
        eType="#//Plugin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnifeSearch"/>
</ecore:EPackage>
