/*
 * generated by Xtext
 */
package org.limepepper.chefclipse.json.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractJsonValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.limepepper.chefclipse.json.json.JsonPackage.eINSTANCE);
		return result;
	}
}
