/**
 * generated by Xtext
 */
package org.limepepper.chefclipse.json.validation;

import org.limepepper.chefclipse.json.validation.AbstractJsonValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JsonValidator extends AbstractJsonValidator {
}
