/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.validation;


/**
 * A sample validator interface for {@link org.limepepper.chefclipse.ChecksumFile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChecksumFileValidator {
	boolean validate();

	boolean validateChecksum(String value);
	boolean validatePath(String value);
	boolean validateSpecificity(String value);
}
