/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.validation;

import java.util.HashMap;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.MapTestContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MapTestContainerValidator {
	boolean validate();

	boolean validateEntries(EList<HashMap> value);
}
