/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.validation;

import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.NameUrlMap}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NameUrlMapValidator {
	boolean validate();

	boolean validateEntries(EMap<String, String> value);
}
