/*
 * generated by Xtext
 */
package org.limepepper.chefclipse.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import chefclipse.core.builders.XTextNatureAddingEditorCallback;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends org.limepepper.chefclipse.json.ui.AbstractJsonUiModule {
	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.IXtextEditorCallback> bindIXtextEditorCallback() {
		return XTextNatureAddingEditorCallback.class;
	}
//	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
//		return QualifiedNameFragmentProvider.class;
//	}

}
