/*
 * generated by Xtext
 */
package org.limepepper.chefclipse.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends org.limepepper.chefclipse.json.ui.AbstractJsonUiModule {
	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
//	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
//		return QualifiedNameFragmentProvider.class;
//	}

}
