/*
 * generated by Xtext
 */
package org.limepepper.chefclipse.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.limepepper.chefclipse.json.JsonXtextResourceSet;

import chefclipse.core.builders.XTextNatureAddingEditorCallback;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends org.limepepper.chefclipse.json.ui.AbstractJsonUiModule {
	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.IXtextEditorCallback> bindIXtextEditorCallback() {
		return XTextNatureAddingEditorCallback.class;
	}
	
	public Class<? extends XtextResourceSet> bindXtextResourceSet() {
		return JsonXtextResourceSet.class;
	}

}
