<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chefclient" nsURI="http://limepepper.org/chefclipse/chefclipse"
    nsPrefix="org.limepepper.chefclipse">
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="ecore:EClass chefserver.ecore#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ohai"/>
  <eClassifiers xsi:type="ecore:EClass" name="Search"/>
</ecore:EPackage>
