<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://limepepper.org/v1/chefclipse/model" nsPrefix="org.limepepper.chefclipse">
  <eClassifiers xsi:type="ecore:EClass" name="ChefContainer" eSuperTypes="#//ChefResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefFile" eSuperTypes="#//ChefResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefFolder" eSuperTypes="#//ChefContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefObject">
    <eOperations name="create">
      <eParameters name="resource" lowerBound="1" eType="#//ChefResource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ChefObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ChefObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//ChefProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChefObjectDefinitionFile" eSuperTypes="#//ChefFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefObjectElementFile" eSuperTypes="#//ChefFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefProject" eSuperTypes="#//ChefContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefResource" eSuperTypes="#//ChefObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" lowerBound="1"
        eType="#//IResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true" defaultValueLiteral="0" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChefWorkspace" eSuperTypes="#//ChefContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeTracker"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IResource" instanceClassName="org.eclipse.core.resources.IResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChefServer" eSuperTypes="#//ChefObject"/>
</ecore:EPackage>
