/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.REST.validation;


/**
 * A sample validator interface for {@link org.limepepper.chefclipse.REST.CookbookListVersionResp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CookbookListVersionRespValidator {
	boolean validate();

	boolean validateUrl(String value);
	boolean validateVersion(String value);
}
