/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.REST.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;
import org.limepepper.chefclipse.REST.CookbookAttributes;
import org.limepepper.chefclipse.REST.CookbookDefinition;
import org.limepepper.chefclipse.REST.CookbookFile;
import org.limepepper.chefclipse.REST.CookbookMetadata;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.REST.CookbookVersionResp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CookbookVersionRespValidator {
	boolean validate();

	boolean validateMaintainer(String value);
	boolean validateCategory(String value);
	boolean validateUpdatedAt(Date value);
	boolean validateCreatedAt(Date value);
	boolean validateLatestVersion(String value);
	boolean validateExternalUrl(String value);
	boolean validateDeprecated(boolean value);
	boolean validateReplacement(String value);
	boolean validateDefinitions(EList<CookbookDefinition> value);
	boolean validateFiles(EList<CookbookFile> value);
	boolean validateAttributes(EList<CookbookAttributes> value);
	boolean validateCookbookName(String value);
	boolean validateVersion(String value);
	boolean validateJsonClass(String value);
	boolean validateChefType(String value);
	boolean validateMetadata(CookbookMetadata value);
	boolean validateName(String value);
	boolean validateDescription(String value);
}
