/**
 *
 * $Id$
 */
package org.limepepper.chefclipse.common.cookbook.validation;

import java.util.Map;

import org.eclipse.emf.common.util.EList;
import org.limepepper.chefclipse.common.chefserver.Environment;
import org.limepepper.chefclipse.common.cookbook.Attributes;
import org.limepepper.chefclipse.common.cookbook.CookbookVersion;
import org.limepepper.chefclipse.common.cookbook.Definition;
import org.limepepper.chefclipse.common.cookbook.File;
import org.limepepper.chefclipse.common.cookbook.Library;
import org.limepepper.chefclipse.common.cookbook.Metadata;
import org.limepepper.chefclipse.common.cookbook.Provider;
import org.limepepper.chefclipse.common.cookbook.Recipe;
import org.limepepper.chefclipse.common.cookbook.Resource;
import org.limepepper.chefclipse.common.cookbook.Root_file;
import org.limepepper.chefclipse.common.cookbook.Template;

/**
 * A sample validator interface for {@link org.limepepper.chefclipse.common.cookbook.CookbookVersion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CookbookVersionValidator {
	boolean validate();

	boolean validateEnvironment(Environment value);

	boolean validateTemplates(EList<Template> value);

	boolean validateRecipes(EList<Recipe> value);

	boolean validateDefinitions(EList<Definition> value);

	boolean validateFiles(EList<File> value);

	boolean validateResources(EList<Resource> value);

	boolean validateLibraries(EList<Library> value);

	boolean validateMetadata(Metadata value);

	boolean validateProviders(EList<Provider> value);

	boolean validateRoot_files(EList<Root_file> value);

	boolean validateAttributes(EList<Attributes> value);

	boolean validateCatalog(String value);

	boolean validateDepends(EList<CookbookVersion> value);

	boolean validateMissing(EList<Map.Entry<String, String>> value);
}
