/*
 * generated by Xtext
 */
package org.limepepper.chefclipse.json.ui.contentassist

import org.limepepper.chefclipse.json.ui.contentassist.AbstractJsonProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class JsonProposalProvider extends AbstractJsonProposalProvider {
}
