/*
 * generated by Xtext
 */
package org.limepepper.chefclipse.json;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonRuntimeModule extends org.limepepper.chefclipse.json.AbstractJsonRuntimeModule {

}
